# Generated by Django 4.0.5 on 2022-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_arrived_late_attendance_leave_early'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
