# Generated by Django 4.0.5 on 2022-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_working_hours',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='working_hours',
            field=models.CharField(max_length=20),
        ),
    ]
